### ISSUE TITLE
Prisma integration ?

### ISSUE THREAD

**Issue by LilaRest** [planetscale/database-js#105]
Hi ! Is it possible to integrate this connector with the Prisma client ? I'm running an app in Cloudflare Pages and so can only send requests through HTTP.

**Comment by nickvanw** [comment]
Hi @LilaRest! This is a great question - support for `database-js` in Prisma is something that the Prisma team will need to prioritize and accomplish. 

They have an open issue on their end: https://github.com/prisma/prisma/issues/15265 - I would highly recommend giving that a follow!

**Comment by LilaRest** [comment]
@nickvanw Yeah, I just found this issue on the Prisma repo few seconds after posting this one, I've all the information I needed now, thanks for taking time to reply :)
