### ISSUE TITLE
WASM / Rust version

### ISSUE THREAD

**Issue by re-thc** [planetscale/database-js#107]
Since edge runtimes have WASM support, it'd be good if there was a planetscale driver in WASM instead of Js. Edge resources are limited so the more savings the better :)

**Comment by filipton** [comment]
I've made rust version that runs on wasm (i've only tested it on cloudflare workers).
[https://github.com/filipton/planetscale-driver](https://github.com/filipton/planetscale-driver)

**Comment by iheanyi** [comment]
I'm going to close this out given that @filipton has made this available. Thanks for your contribution!
