### ISSUE TITLE
Parse Date, timezone problem because Z is removed

### ISSUE THREAD

**Issue by roelandmoors** [planetscale/database-js#108]
There is a sanitiser that removes the Z from a date:
https://github.com/planetscale/database-js/blob/c0159c5fa6d903a76edea2c4bb28a73f7bd20f81/src/sanitization.ts#L47

But when I parse that string back to a date I get the wrong result. I needed to add the Z back to make it work:

`new Date(Date.parse(d + "Z"));`

I had that problem here:
https://github.com/roelandmoors/authjs-adapter-mysql/blob/5867a205154f91c88086c0ce2a5101e79c61faf7/src/db.ts#L45

Seems like a bug to me?

**Comment by dgraham** [comment]
See https://github.com/planetscale/database-js/pull/64.

**Comment by roelandmoors** [comment]
I now have a Date to string conversion like below. This way the Z can be stripped without a problem.
```js
export function datetimeToStr(d) {
  const tzoffset = d.getTimezoneOffset() * 60000; //offset in milliseconds
  return new Date(d.getTime() - tzoffset).toISOString().slice(0, -1);
}
```
