### ISSUE TITLE
PlanetScale migrate

### ISSUE THREAD

**Issue by gederer** [planetscale/database-js#113]
Is there a way to use the Drizzle ORM `migrate` API with PlanetScale?

I tried:

```typescript
import { drizzle } from "drizzle-orm/mysql2";
import { migrate } from "drizzle-orm/mysql2/migrator";
import mysql from "mysql2/promise";

async function main() {
  // create the connection
  const poolConnection = mysql.createPool({
    host: process.env.MYSQL_HOSTNAME,
    user: process.env.MYSQL_USERNAME,
    database: process.env.MYSQL_DATABASE,
    multipleStatements: true,
  });

  const db = drizzle(poolConnection);

  // this will automatically run needed migrations on the database
  await migrate(db, { migrationsFolder: "./migrations" });
}
 main();
```

But, I got `code: 'ECONNREFUSED'`. I have confirmed that the stuff in my env is all good.

Thanks!

**Comment by mattrobenolt** [comment]
I'm not sure the error based on this information alone, but none of what I'm seeing here is using this `database-js` driver.

Can you either ask in https://github.com/planetscale/discussion/discussions or open a support ticket? Seems like there's something else going on.
