### ISSUE TITLE
How to close connection?

### ISSUE THREAD

**Issue by Ganesh1991** [planetscale/database-js#114]
`import { connect } from "@planetscale/database";
const conn = connect(config);
export const executeQuery = async (query, params = []) => {
  try {
    const results = await conn.execute(query, params);
    return results;
  } catch (error) {
    console.error(`Error in executeQuery ${error.message}`);
    console.error(`Error in executeQuery ${error.stack}`);
    throw error;
  }
};
`
How does connection handling work and how to close the existing database connection?

**Comment by mattrobenolt** [comment]
There's no ability or need to explicitly close any connections. The `connect(..)` function doesn't actually establish a connection, it's just to surface a familiar API and concept.

The underlying connection is managed by the JavaScript runtime through the `fetch()` API. Different fetch() implementations might behave differently, but it's up to that implementation. We don't explicitly manage network connections, or need to.
