### ISSUE TITLE
[Question] question about performance

### ISSUE THREAD

**Issue by shiyuhang0** [planetscale/database-js#116]
I have learned that this driver is based on the unpublished HTTP API. I'm curious about its performance since it's HTTP based.

Is there any performance comparison between this serverless driver and other TCP based drivers like [mysql2](https://github.com/sidorares/node-mysql2). thanks!

**Comment by iheanyi** [comment]
We didn't do any benchmarking of this package specifically. But check out [this blog post](https://planetscale.com/blog/faster-mysql-with-http3) by @mattrobenolt about the benchmarking of each protocol

**Comment by shiyuhang0** [comment]
Thanks, this blog helps a lot. Does the driver uses the HTTP/3 API introduced in this post?
