### ISSUE TITLE
INVISIBLE columns showing up with SELECT *

### ISSUE THREAD

**Issue by cdcarson** [planetscale/database-js#146]
I noticed the other day that `SELECT *` queries were coming back with columns I've marked as `INVISIBLE` included. I'm sure this was not the case the last time I paid attention, a few months ago. That is, INVISIBLE columns were omitted. I can do without it, but `INVISIBLE` is a convenient way to exclude stuff based on security concerns or optimization.

This might not be the right place to file this issue -- the behavior is the same using a mysql driver -- but this is the library I'm using. Maybe related upstream: https://github.com/vitessio/vitess/issues/9783.

Reproduction:

```sql

CREATE TABLE `UserLogin` (
  `userId` bigint unsigned NOT NULL,
  `email` varchar(320) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL /*!80023 INVISIBLE */,
  PRIMARY KEY (`userId`),
  UNIQUE KEY `UserLogin_email_key` (`email`),
  KEY `UserLogin_userId_idx` (`userId`)
);

SHOW COLUMNS FROM UserLogin;
+----------+-----------------+------+-----+---------+-----------+
| Field    | Type            | Null | Key | Default | Extra     |
+----------+-----------------+------+-----+---------+-----------+
| userId   | bigint unsigned | NO   | PRI | NULL    |           |
| email    | varchar(320)    | NO   | UNI | NULL    |           |
| password | varchar(191)    | NO   |     | NULL    | INVISIBLE |
+----------+-----------------+------+-----+---------+-----------+

INSERT INTO UserLogin (`userId`, `email`, `password`) VALUES (1, 'foo@bar.com', 'hashed IRL');
SELECT * FROM UserLogin WHERE userId = 1;
+--------+-------------+------------+
| userId | email       | password   |
+--------+-------------+------------+
|      1 | foo@bar.com | hashed IRL |
+--------+-------------+------------+

```

**Comment by mattrobenolt** [comment]
Ok, and behavior against vanilla mysql 8.0.29, it behaves how you're suggesting.

```
mysql> SELECT * FROM UserLogin WHERE userId = 1;
+--------+-------------+
| userId | email       |
+--------+-------------+
|      1 | foo@bar.com |
+--------+-------------+
1 row in set (0.01 sec)
```

**Comment by cdcarson** [comment]
@mattrobenolt Yeah, it's definitely upstream from this library. On the off-chance it wasn't, I tried downgrading to @planetscale/database to 1.8 and 1.6, versions where I know that `INVISIBLE` was working as expected at the time, and same deal -- the columns are included. So it's something with Vitess or PlanetScale's implementation.

As I said, I can work around this. But if it can't be fixed maybe the [MySQL compatibility page](https://planetscale.com/docs/reference/mysql-compatibility) can be updated. 

Thanks!

**Comment by cdcarson** [comment]
I just noticed this seems to be fixed at least on my PlanetScale database, i.e., `INVISIBLE` columns are omitted with `SELECT *`.  

Is it fixed or am I jumping the gun?  Thanks.
