### ISSUE TITLE
Numbers returned as strings

### ISSUE THREAD

**Issue by twiddler** [planetscale/database-js#175]
In the following test suite, when using `PlanetScaleDialect` and receiving more than one row, what I expected to be numbers is parsed as strings instead:

```ts
import { Kysely, MysqlDialect } from "kysely";
import { PlanetScaleDialect } from "kysely-planetscale";
import { createPool } from "mysql2";
import { strict as assert } from "node:assert";
import { describe, test } from "node:test";
import { fetch } from "undici";

describe("mysql", function () {
  const db = new Kysely({
    dialect: new MysqlDialect({
      pool: createPool({
        database: "mysql",
        host: "localhost",
        user: "root",
        password: "",
      }),
    }),
  });

  test("one row", async function () {
    const q = await db
      .selectFrom([
        db.selectNoFrom((eb) => eb.val(0).as("num_column")).as("foo"),
      ])
      .selectAll()
      .execute();

    assert.deepStrictEqual(q, [{ num_column: 0 }]); // ✅
  });

  test("two rows", async function () {
    const q = await db
      .selectFrom([
        db
          .selectNoFrom((eb) => eb.val(0).as("num_column"))
          .unionAll(db.selectNoFrom((eb) => eb.val(0).as("num_column")))
          .as("foo"),
      ])
      .selectAll()
      .execute();

    assert.deepStrictEqual(q, [{ num_column: 0 }, { num_column: 0 }]); // ✅
  });
});

describe("planetscale", function () {
  const db = new Kysely({
    dialect: new PlanetScaleDialect({
      url: process.env.PLANETSCALE_URL,
      fetch,
    }),
  });

  test("one row", async function () {
    const q = await db
      .selectFrom([
        db.selectNoFrom((eb) => eb.val(0).as("num_column")).as("foo"),
      ])
      .selectAll()
      .execute();

    assert.deepStrictEqual(q, [{ num_column: 0 }]); // ✅
  });

  test("two rows", async function () {
    const q = await db
      .selectFrom([
        db
          .selectNoFrom((eb) => eb.val(0).as("num_column"))
          .unionAll(db.selectNoFrom((eb) => eb.val(0).as("num_column")))
          .as("foo"),
      ])
      .selectAll()
      .execute();

    assert.deepStrictEqual(q, [{ num_column: 0 }, { num_column: 0 }]); // ❌ actual: [ { num_column: '0' }, { num_column: '0' } ]
  });
});
```

Gist for reproducing: https://gist.github.com/twiddler/8f98b48ec61c75eaa5422249c1edebc9. Please set `PLANETSCALE_URL` in `.env` and use Node 21 or later.

Is this expected behavior?

**Comment by mattrobenolt** [comment]
I suspect it's because your schema contains bigints or some other unsigned 64 bit integer which isn't representable in JavaScript.

We have an example specifically for doing your own casting to a JS BigInt type. https://github.com/planetscale/database-js?tab=readme-ov-file#custom-type-casting-function

The proposal to use BigInts directly was rejected. https://github.com/planetscale/database-js/pull/90

**Comment by iheanyi** [comment]
https://github.com/planetscale/database-js?tab=readme-ov-file#custom-type-casting-function

As linked above, you can use a custom casting function for addressing this. Rather than forcing usage of BigInt, you can opt into it.

**Comment by twiddler** [comment]
@mattrobenolt There's no schema involved. I am doing

```sql
SELECT * FROM
  (
    SELECT 0 AS "num_column"
    UNION ALL
    SELECT 0 AS "num_column"
  ) AS "foo"
  ```

(Sorry if that wasn't clear from the code. I originally posted this on [kysely-planetscale](https://github.com/depot/kysely-planetscale/issues/30).)

What puzzles me is that the type changes depending on how many lines the result set has. It'd be fine if it was always BigInts passed as strings. But if it's sometimes strings, sometimes numbers it makes it really hard to trace errors.

**Comment by mattrobenolt** [comment]
Oh, I did miss that. Lemme see what MySQL is doing here.

**Comment by mattrobenolt** [comment]
This example is now different though than what you first produced. The first examples yield a "derived table" which is what's behaving oddly.

Can you give me a schema that you're working with for this latter example actually doing a LEFT JOIN? I'm curious to see the data types Vitess is returning vs MySQL. It might be that we're doing something wrong here.

**Comment by mattrobenolt** [comment]
I tried to reproduce with the following:

```sql
CREATE TABLE A (
    id bigint unsigned AUTO_INCREMENT,
    PRIMARY key(id)
);

CREATE TABLE B (
    id bigint unsigned AUTO_INCREMENT,
    aId bigint unsigned,
    foo text,
    PRIMARY key(id),
    KEY(aId)
);

INSERT INTO A VALUES(NULL);
INSERT INTO A VALUES(NULL);
INSERT INTO B VALUES (NULL, 1, 'hello');

SELECT
    B.foo,
    B.aId IS NOT NULL AS matchFound
FROM
    A LEFT JOIN B
ON
    A.id = B.aId;
```

This setup seems to mirror what you're trying to accomplish.

Against PlanetScale, I get:

```
mysql> SELECT
    ->     B.foo,
    ->     B.aId IS NOT NULL AS matchFound
    -> FROM
    ->     A LEFT JOIN B
    -> ON
    ->     A.id = B.aId;
Field   1:  `foo`
Catalog:    `def`
Database:   `mattdb`
Table:      `B`
Org_table:  `B`
Type:       BLOB
Collation:  utf8mb4_0900_ai_ci (255)
Length:     262140
Max_length: 5
Decimals:   0
Flags:      BLOB

Field   2:  `matchFound`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     1
Max_length: 1
Decimals:   0
Flags:      NOT_NULL BINARY NUM
```

And against vanilla MySQL 8.0.34:

```
mysql> SELECT
    ->     B.foo,
    ->     B.aId IS NOT NULL AS matchFound
    -> FROM
    ->     A LEFT JOIN B
    -> ON
    ->     A.id = B.aId;
Field   1:  `foo`
Catalog:    `def`
Database:   `mysql`
Table:      `B`
Org_table:  `B`
Type:       BLOB
Collation:  utf8mb4_general_ci (45)
Length:     262140
Max_length: 5
Decimals:   0
Flags:      BLOB

Field   2:  `matchFound`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     1
Max_length: 1
Decimals:   0
Flags:      NOT_NULL BINARY NUM


+-------+------------+
| foo   | matchFound |
+-------+------------+
| hello |          1 |
| NULL  |          0 |
+-------+------------+
2 rows in set (0.00 sec)
```

If I delete a row, so there's only 1:

```
--- PlanetScale
mysql> delete from A where id=2;
Query OK, 1 row affected (0.11 sec)

mysql> SELECT
    ->     B.foo,
    ->     B.aId IS NOT NULL AS matchFound
    -> FROM
    ->     A LEFT JOIN B
    -> ON
    ->     A.id = B.aId;
Field   1:  `foo`
Catalog:    `def`
Database:   `mattdb`
Table:      `B`
Org_table:  `B`
Type:       BLOB
Collation:  utf8mb4_0900_ai_ci (255)
Length:     262140
Max_length: 5
Decimals:   0
Flags:      BLOB

Field   2:  `matchFound`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     1
Max_length: 1
Decimals:   0
Flags:      NOT_NULL BINARY NUM


+-------+------------+
| foo   | matchFound |
+-------+------------+
| hello |          1 |
+-------+------------+
1 row in set (0.10 sec)
```

```
--- MySQL 8.0.34
mysql> delete from A where id=2;
Query OK, 1 row affected (0.02 sec)

mysql> SELECT
    ->     B.foo,
    ->     B.aId IS NOT NULL AS matchFound
    -> FROM
    ->     A LEFT JOIN B
    -> ON
    ->     A.id = B.aId;
Field   1:  `foo`
Catalog:    `def`
Database:   `mysql`
Table:      `B`
Org_table:  `B`
Type:       BLOB
Collation:  utf8mb4_general_ci (45)
Length:     262140
Max_length: 5
Decimals:   0
Flags:      BLOB

Field   2:  `matchFound`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     1
Max_length: 1
Decimals:   0
Flags:      NOT_NULL BINARY NUM


+-------+------------+
| foo   | matchFound |
+-------+------------+
| hello |          1 |
+-------+------------+
1 row in set (0.00 sec)
```

In all cases, `matchFound` is a `LONGLONG` which is a 64 bit integer.

Am I missing something here? This would yield a string in all cases through our driver.

**Comment by jacobwgillespie** [comment]
@twiddler one thing to watch for: I think the `mysql2` client is going to type-cast values as either numbers or strings based on the length of the string returned, basically if the string value of the number is short enough, it'll automatically parse it into a number:

https://github.com/sidorares/node-mysql2/blob/225a2bdb6e16ee201121d4a8d36508a792ff6e54/lib/packets/packet.js#L433-L487

There's some pool options that control that behavior (e.g. setting `bigNumberStrings: true` will mean that the `LONGLONG` always gets returned as a string), but that might be the source of the difference here.

**Comment by twiddler** [comment]
Thanks for all your hard work, and sorry for getting back so late. :pray: 

> the mysql2 client is going to type-cast values as either numbers or strings based on the length of the string returned

That would have explained the behaviour, but even with

```diff
      pool: createPool({
        database: "mysql",
        host: "localhost",
        user: "root",
        password: "",
+       bigNumberStrings: true,
      }),
 ```

the tests in my opening post still pass:

```
▶ mysql
  ✔ one row (30.003698ms)
  ✔ two rows (1.971407ms)
▶ mysql (32.916212ms)
```

Expecting strings fails:

```diff
-   assert.deepStrictEqual(q, [{ num_column: 0 }, { num_column: 0 }]);
+   assert.deepStrictEqual(q, [{ num_column: "0" }, { num_column: "0" }]);
```

```
▶ mysql
  ✔ one row (33.345367ms)
  ✖ two rows (5.137187ms)
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
```

> Can you give me a schema that you're working with for this latter example actually doing a LEFT JOIN?

```sql
CREATE TABLE `A` (
  `id` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `B` (
  `id` varchar(191) NOT NULL,
  `aId` varchar(191) NOT NULL,
  `foo` enum('inherit', 'true', 'false') NOT NULL DEFAULT 'inherit',
  PRIMARY KEY (`id`, `aId`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;
```

And the query (for convenience, same as [above](https://github.com/planetscale/database-js/issues/175#issuecomment-2091164108)):

```sql
SELECT
  B.foo,
  B.aId IS NOT NULL as matchFound
FROM
  A LEFT JOIN B
ON
  A.id = B.aId;
```

**Comment by twiddler** [comment]
So while I am still confused why mysql2 didn't behave as expected when `bigNumberStrings: true`, I am sure that when it comes to PlanetScale I can solve my use case with a [custom cast function](https://github.com/depot/kysely-planetscale#custom-cast-function). (In my application, I see no reason to just `Number(...)` any numeric value and then assert it is `<= Number.MAX_SAFE_INTEGER`--which is ridiculously huge anyway.)

I can't figure out why MySQL treats `IS NOT NULL` as an INT64, but that question is certainly out of scope here. [`CAST`](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast) does not accept any smaller number type, so I'll select `B.aId` and [`z.transform`](https://github.com/colinhacks/zod?tab=readme-ov-file#transform) `null` to `false` and everything else to `true`.

Thanks for all your input. This was definitely an interesting ride. :roller_coaster:

**Comment by mattrobenolt** [comment]
Yeah, I can't explain why MySQL behaves that way either. Or why mysql2 infers this. But they definitely do extra work to try and coerce numbers. Maybe it's something we can explore too? But that seems like it'd have unexpected behaviors too. When you do cross the boundary, now you get a string.

I can easily see the case where you have a bigint primary key, everything is working for a long time. Eventually you cross the threshold and now you get strings back and code is broken. I'm not sure that'd be a good experience either.

I'd personally recommend, like you suggested, a custom cast function or something for you to explicitly handle this how you want to.

I think we as a library are handling this as correctly as we can in JavaScript until we have some evidence otherwise.
