### ISSUE TITLE
VT12001: unsupported: subqueries in DML when using delete() with where that filters on relation field

### ISSUE THREAD

**Issue by zbeyens** [planetscale/database-js#178]
## Problem

I'm having this error when running 

```tsx
await prisma.characterEducation.delete({
        where: {
          Character: {
            userId: ctx.userId,
          },
          id: input.id,
        },
      });
```

> prisma:error VT12001: unsupported: subqueries in DML

Using `prisma 5.11.0` and planetscale driver.

It has been well analyzed by https://github.com/prisma/prisma/issues/23603#issuecomment-2088123888 where the solution would be to implement vitess's fix in https://github.com/vitessio/vitess/pull/15219

**Comment by dbussink** [comment]
This is not something that's a bug or issue with this driver. The fix should be available on an internal pre-release version for PlanetScale, you can contact our support team if you want your database to be upgraded ahead of the curve to get this fix.
