### ISSUE TITLE
Reject promise if query fails

### ISSUE THREAD

**Issue by shyim** [planetscale/database-js#61]
Hey,

I would currently expect that when a query fails, the promise will be rejected. Maybe with a new config `rejectPromiseIfQueryFails: boolean`

Thanks for building this. Works awesome with Cloudflare Workers

**Comment by iheanyi** [comment]
Thanks for opening this issue! This is instead of returning an error object, right? This is good feedback, thank you!

**Comment by shyim** [comment]
Yes.

I use very often just ``await execute('DELETE FROM xxx')`` and I don't need to look into the response. Only if its not working 😅
