### ISSUE TITLE
Doesn't work with jest

### ISSUE THREAD

**Issue by OultimoCoder** [planetscale/database-js#70]
Please see #68 It was never fixed and using the minimal example provided it still errors. This is blocking me really hard if anyone could help me that would be great! Thanks

**Comment by iheanyi** [comment]
Could you post the error output that you are getting please so we can help debug?

**Comment by tbarn** [comment]
Hey @OultimoCoder! I'm going to close this for right now, but if you have errors to share that can help with debugging, please do share.
