### ISSUE TITLE
How to specify a timeout

### ISSUE THREAD

**Issue by goenning** [planetscale/database-js#87]
How do I define a timeout for queries? I want to avoid a potentially long running query

**Comment by iheanyi** [comment]
While there is currently no way of supplying a custom timeout, all queries have a timeout of 30 seconds before returning an error. You can read more about our system limitations in our [documentation](https://planetscale.com/docs/reference/planetscale-system-limits#recommendations-for-handling-query-limits).

**Comment by iheanyi** [comment]
I did some more asking around internally and you can also already specify a timeout on `SELECT` queries using the `QUERY_TIMEOUT_MS` [comment directive](https://vitess.io/docs/16.0/user-guides/configuration-advanced/comment-directives/#query-timeouts-query_timeout_ms). This may be helpful for you if you want to customize timeouts for specific queries.
