### ISSUE TITLE
How to select what branch to connect to

### ISSUE THREAD

**Issue by DominicTobias** [planetscale/database-js#94]
Hi, it seems that my connection points to the production database. How can I point to a development branch instead?

I'm using separate host/username/password. There is no option to select a branch. Am I supposed to switch to a URL string and connect via a pscale proxy locally?

Thanks

**Comment by mscoutermarsh** [comment]
Hi @DominicTobias,

To grab your development branch connection string. Go to the `Branches` tab. Then click your development branch. Click `connect` on the top right to get credentials for that branch.
