### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by twiddler** [planetscale/database-js#96]
I can't find the changelog for v1.6.0 (or any version, really). Can someone tell me where to look? Thanks. :pray:

**Comment by iheanyi** [comment]
Hey there!

Apologies for the delay on this and also the missing release notes. We had a gap in our release workflow where we weren't creating releases for each newly published version. I've gone ahead and backfilled the releases for every single published version, in addition to making a note in our workflow to cut a new release after we publish a new version going forward. Thanks for bringing it up and helping us improve our things, I hope it's helpful!
