### ISSUE TITLE
Empty result when querying from Next.js App Router component

### ISSUE THREAD

**Issue by dorshinar** [planetscale/database-js#99]
Hi!
I'm trying to setup a new Next.js project with PlanetScale using the new Next.js App Router. 
I'm facing a problem where querying the DB from a script works fine, but sending the same query from a component returns an empty result. 
In the following image the first log is from the server startup running in a separate scripts, and the second and third logs are when I call the function from a component. 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/17943918/229622707-64f2ed9c-0557-4824-adcc-471d7550679c.png">
[Here's](https://github.com/dorshinar/shopshop/blob/drizzle/src/app/page.tsx) a link to the repo, it's quite bare-bone. 

Thank you very much!

**Comment by iheanyi** [comment]
When it comes down to this, you probably want to call the database API from within `[getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)` and then passing that down into your component. Rather than making a call to that database client-side. Does that work?

**Comment by dorshinar** [comment]
No, I'm using Next's new App Router which lets you query from React Server Components. That is not a client-side fetch.

**Comment by kraffslol** [comment]
I was looking through the nextjs docs and found this part regarding the fetch function:
> React extends fetch to provide [automatic request deduping](https://beta.nextjs.org/docs/data-fetching/fundamentals#automatic-fetch-request-deduping), and Next.js extends the fetch options object to allow each request to set its own [caching and revalidating](https://beta.nextjs.org/docs/data-fetching/caching).

and

> By default, fetch will automatically fetch and [cache data](https://beta.nextjs.org/docs/data-fetching/caching) indefinitely.

Could it be that the query response is being cached? Can you try adding
`export const revalidate = 1;`
to page.tsx and see if it makes a difference?

**Comment by mattrobenolt** [comment]
If it helps with debugging, all of our requests are a POST. Typically POST requests skip caching, at least I'd hope so. I know absolutely nothing about Next.js tho.

I'm strongly inclined to think this isn't an issue with Drizzle or database-js, and seems likely it's just being used incorrectly in this context?

**Comment by kraffslol** [comment]
Yes this issue doesn't seem to be related to Drizzle or database-js. But rather Nextjs caching the responses from fetch in React Server Components. The solution seems to be either setting `export const revalidate = 0;` on the page component, or providing a custom fetch function to database-js (haven't tried this).

**Comment by dorshinar** [comment]
Yeah, you are correct. `export const revalidate = 0;` does seem to fix that, even though the Next.js docs say they don't cache post requests. 
Thank you for your help! You can close this one :)
